[package]
name = "faiss-next"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faiss-next-sys = { version = "0.4.0", path = "./faiss-next-sys" }
thiserror = "1.0.58"

[workspace]
members = ["faiss-next-sys"]
