workspace = { members = ["faiss-next-sys"] }

[package]
name = "faiss-next"
version = "0.4.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
faiss-next-sys = { version = "0.4.0", path = "./faiss-next-sys" }
itertools = "0.13.0"
thiserror = "1.0.63"

[dev-dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
