[package]
name = "faiss-next"
version = "0.4.0"
edition = "2021"

[features]
default = []
gpu = ["faiss-next-sys/gpu"]

[dependencies]
smart-default = "0.7.1"
thiserror = "1.0.56"

[dev-dependencies]
rand = "0.8.5"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.faiss-next-sys]
path = "faiss-next-sys"
version = "0.4.0"


[workspace]
members = ["faiss-next-sys"]
