[package]
name = "faiss-next"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0.119", features = ["c++17"] }
num_enum = "0.7.2"
smart-default = "0.7.1"
thiserror = "1.0.57"
tracing = "0.1.40"

[build-dependencies]
cxx-build = "1.0.119"

[dev-dependencies]
tracing-subscriber = "0.3.18"
