[package]
name = "faiss-next"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
gpu = []

[build-dependencies]
bindgen = "0.69.2"
cfg-if = "1.0.0"

[dependencies]
thiserror = "1.0.56"
tracing = "0.1.40"

[dev-dependencies]
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
tracing-subscriber = "0.3.18"
