[package]
name = "faiss-next-sys"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
bindgen = []

[dependencies]


[build-dependencies]
bindgen = "0.69.4"
