[package]
edition = "2021"
name = "faiss-next-sys"
version = "0.4.0"

[dependencies]
cxx = "1.0.126"

[build-dependencies]
bindgen = "0.70.0"
cxx-build = "1.0.126"

[features]
default = []
bindgen = []
cuda = []
