[package]
name = "faiss-next-sys"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
anyhow = "1.0.81"

[features]
default = []
bindgen = []
gpu = []
