#include "faiss/c_api/AutoTune_c.h"
#include "faiss/c_api/clone_index_c.h"
#include "faiss/c_api/Clustering_c.h"
#include "faiss/c_api/error_c.h"
// #include "faiss/c_api/error_impl.h"
#include "faiss/c_api/faiss_c.h"
#include "faiss/c_api/impl/AuxIndexStructures_c.h"
#include "faiss/c_api/IndexBinary_c.h"
#include "faiss/c_api/Index_c.h"
#include "faiss/c_api/index_factory_c.h"
#include "faiss/c_api/IndexFlat_c.h"
#include "faiss/c_api/index_io_c.h"
#include "faiss/c_api/IndexIVF_c.h"
#include "faiss/c_api/IndexIVFFlat_c.h"
#include "faiss/c_api/IndexLSH_c.h"
#include "faiss/c_api/IndexPreTransform_c.h"
#include "faiss/c_api/IndexReplicas_c.h"
#include "faiss/c_api/IndexScalarQuantizer_c.h"
#include "faiss/c_api/IndexShards_c.h"
// #include "faiss/c_api/macros_impl.h"
#include "faiss/c_api/MetaIndexes_c.h"
#include "faiss/c_api/utils/distances_c.h"
#include "faiss/c_api/VectorTransform_c.h"
#ifdef FAISS_USE_GPU
#include "faiss/c_api/gpu/DeviceUtils_c.h"
#include "faiss/c_api/gpu/GpuAutoTune_c.h"
#include "faiss/c_api/gpu/GpuClonerOptions_c.h"
#include "faiss/c_api/gpu/GpuIndex_c.h"
#include "faiss/c_api/gpu/GpuIndicesOptions_c.h"
#include "faiss/c_api/gpu/GpuResources_c.h"
// #include "faiss/c_api/gpu/macros_impl.h"
#include "faiss/c_api/gpu/StandardGpuResources_c.h"
#endif